[2023-12-20 23:50:56,652] 96 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.29.68:5000
[2023-12-20 23:50:56,652] 96 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
[2023-12-20 23:51:04,972] 96 - werkzeug - INFO - 127.0.0.1 - - [20/Dec/2023 23:51:04] "GET / HTTP/1.1" 200 -
[2023-12-20 23:51:08,602] 96 - werkzeug - INFO - 127.0.0.1 - - [20/Dec/2023 23:51:08] "GET /predict HTTP/1.1" 200 -
[2023-12-20 23:51:32,759] 825 - app - ERROR - Exception on /predict [POST]
Traceback (most recent call last):
  File "app.py", line 27, in predict_datapoint
    reading_score=float(request.form.get('writing score')),
TypeError: float() argument must be a string or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Git-1\mlproject\venv\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\Git-1\mlproject\venv\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\Git-1\mlproject\venv\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\Git-1\mlproject\venv\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 40, in predict_datapoint
    raise CustomException(e,sys)
src.exception.CustomException: Error occurred in python script name [app.py] line number [27] error message [float() argument must be a string or a number, not 'NoneType']
[2023-12-20 23:51:32,766] 96 - werkzeug - INFO - 127.0.0.1 - - [20/Dec/2023 23:51:32] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
